[package]
name = "basic-app"
version = "0.1.0"
edition = "2021"

[dependencies]
astrea = { path = ".." }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.49", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
